# Generated by Django 4.2.16 on 2025-01-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmykid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('contact', models.IntegerField()),
                ('child_photo', models.ImageField(upload_to='media/evidence')),
            ],
        ),
    ]
