# Generated by Django 4.2.16 on 2025-01-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmykid', '0002_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='child_name',
            field=models.CharField(default='John Doe', max_length=256),
        ),
    ]
