# Generated by Django 5.1.2 on 2025-01-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmykid', '0003_evidence_child_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='child_name',
            field=models.IntegerField(),
        ),
    ]
