# Generated by Django 5.1.2 on 2025-01-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findmykid', '0004_alter_evidence_child_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='child_name',
            new_name='child_id',
        ),
    ]
