# Generated by Django 5.1.2 on 2025-01-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmykid', '0005_rename_child_name_evidence_child_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='child_id',
        ),
        migrations.AddField(
            model_name='evidence',
            name='child_firstName',
            field=models.CharField(default='John Doe', max_length=256),
        ),
    ]
